version: '3'
services:
  zookeeper:
    platform: linux/amd64
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    expose:
      - "2181"
    networks:
      - kafka-net
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka1:
    platform: linux/amd64
    image: wurstmeister/kafka:0.10.0.1
    ports:
      - "9092:9092"
    expose:
      - "9092"
    networks:
      - kafka-net
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  webhookd:
    image: davidoram/webhookd
    networks:
      - kafka-net
    depends_on:
      - kafka1
    volumes:
      - ./data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 5s

  csv-publish:
    image: davidoram/csv-publish
    networks:
      - kafka-net
    depends_on:
      - kafka1
    volumes:
      - ./data:/data

  test-endpoint:
    image: davidoram/test-endpoint
    networks:
      - kafka-net
    depends_on:
      webhookd:
        condition: service_healthy
    volumes:
      - ./data:/data

networks:
  kafka-net:
    driver: bridge
